/**
 * Author: Harsh Maisuri
 */

export const GET_CUSTOMER_PROFILE = "GET_CUSTOMER_PROFILE";
export const GET_SELLER_PROFILE = "GET_SELLER_PROFILE";
export const EDIT_CUSTOMER_PROFILE = "EDIT_CUSTOMER_PROFILE";
